### ISSUE TITLE
OS X build

### ISSUE THREAD

**Issue by rseymour** [intel/fMBT#40] opened 2015-06-10 03:36 UTC
I managed to get fMBT to build and run on OS X native.  I unfortunately did it on a whim (while on vacation) and it's a total hack, but I rebased it off of devel and have it here:

https://github.com/rseymour/fMBT/tree/osx-build

I will see if I can ifdef some things and make it build properly without viciously deleting things. Once I can get it to reliably build on OSX and Linux I'll write up a deps.

And here's a screenshot for proof. :apple: 
![image](https://cloud.githubusercontent.com/assets/105805/8074412/3fce1aaa-0f00-11e5-9cd6-1013b63b0fc3.png)

**Comment by askervin** [comment] 2015-06-10 14:00
This is great news, @rseymor! I'm happy to see that not too many changes were needed to get the basics working. I wouldn't be very surprised, though, if self tests (make check) or fmbt-scripter and some GUI test interfaces would cause extra pain. But don't worry about those yet. They have some issues on Windows, too, and still there are Windows users.

I'm looking forward what you'll come up with.

**Comment by memoselyk** [comment] 2017-10-26 06:45
To get the package compiling on Mac (with homebrew) Imagemagick 6.x is required. Otherwise the following error is encountered:

```
fatal error: 'magick/MagickCore.h' file not found
```

On Imagemagick 7 the headers location [has changed](https://www.imagemagick.org/script/porting.php#headers).

I followed [this instructions](https://sites.google.com/site/zhoubx/computer/ruby/zai-mac-os-x-yosemite-10-10-2-an-zhuang-rmagick) to install a compatible version:

``` 
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6f014f2b7f1f9e618fd5c0ae9c93befea671f8be/Formula/imagemagick.rb
```

**Comment by AndrewO** [comment] 2020-03-01 04:15
I just tried to build and ran into 3 issues (2 of which I solved):

1. `libedit` missing. Solution: `brew install libedit` and add it to `PKG_CONFIG_PATH`. Homebrew reports that OS X comes with one, but `./configure` couldn't find it otherwise.
2. The ImageMagick 7 issue @memoselyk mentioned. Solution: `brew install imagemagick@6` and add it to `PKG_CONFIG_PATH`.
3. I'm currently stuck on some `clang` errors:

```
test_engine.cc:641:27: error: ordered comparison between pointer and zero ('std::__1::__vector_base<End_condition *,
      std::__1::allocator<End_condition *> >::value_type' (aka 'End_condition *') and 'int')
              if (atags[i]>0)
                  ~~~~~~~~^~
test_engine.cc:648:27: error: ordered comparison between pointer and zero ('std::__1::__vector_base<End_condition *,
      std::__1::allocator<End_condition *> >::value_type' (aka 'End_condition *') and 'int')
              if (atags[i]>0)
                  ~~~~~~~~^~
test_engine.cc:672:27: error: ordered comparison between pointer and zero ('std::__1::__vector_base<End_condition *,
      std::__1::allocator<End_condition *> >::value_type' (aka 'End_condition *') and 'int')
              if (etags[i]>0)
                  ~~~~~~~~^~
test_engine.cc:679:27: error: ordered comparison between pointer and zero ('std::__1::__vector_base<End_condition *,
      std::__1::allocator<End_condition *> >::value_type' (aka 'End_condition *') and 'int')
              if (etags[i]>0)
                  ~~~~~~~~^~
```

[This blog](http://sylvestre.ledru.info/blog/2017/08/24/rebuild-of-debian-using-clang-2) mentions that Clang 4.0 introduced this error, but doesn't say if/how it can be relaxed. Everything else I see suggests changing the source code.

**Comment by askervin** [comment] 2020-03-02 08:39
Hi @AndrewO! Thanks for reporting. I was able to reproduce this this compiler error with clang 9.0.1 on my Linux environment. It's fixed in the devel branch,  commit 07f291e8ba44b912b55cfdc1899e1a7831bd5dad.

**Comment by AndrewO** [comment] 2020-03-02 14:03
Thanks!

I just pulled `devel` and now I'm getting this:

```
In file included from ./adapter_remote.hh:21:
./remote.hh:107:9: error: use of undeclared identifier 'WCOREDUMP'
    if (WCOREDUMP(status)) {
        ^
```

**Comment by askervin** [comment] 2020-03-02 14:52
Something must have hidden the `WCOREDUMP` macro in `sys/wait.h`.
I pushed commit 72cad3badf7b97a287020cd0b58b5105a72ff0e9 to the devel branch to enable compiling without the macro. But I think it would be actually nicer to make it somehow visible, if it's there in OS X. Unfortunately I don't have that environment, so let's continue with this way...

**Comment by fkberthold** [comment] 2020-09-08 02:56
I'm attempting to build on a MacOS machine, and seem to be having an ImageMagick issue:

```
touch utils_installer
VPATH='.' CC='g++' PKG_CONFIG='/usr/local/bin/pkg-config' with_imagemagick='yes' /usr/local/bin/python setup.py build
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    eye4graphcs_buildflags = pkg_config("MagickCore")
  File "setup.py", line 68, in pkg_config
    % (arg, o))
ValueError: Unexpected pkg-config output: "-Xpreprocessor" in "-Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.10-29/include/ImageMagick-7 -L/usr/local/Cellar/imagemagick/7.0.10-29/lib -lMagickCore-7.Q16HDRI
"
```

Are there any suggestions for how to move forward?

**Comment by askervin** [comment] 2020-09-08 06:38
> -I/usr/local/Cellar/imagemagick/7.0.10-29/include/ImageMagick-7

This looks like the build is trying to use ImageMagick 7. Unfortunately ImageMagick API has changed from 6 to 7, and fMBT has been developed with version 6.

I hope @AndrewO's tip in [a previous comment](https://github.com/intel/fMBT/issues/40#issuecomment-593051419) helps:

> Solution: `brew install imagemagick@6` and add it to `PKG_CONFIG_PATH`

**Comment by fkberthold** [comment] 2020-09-08 15:14
@askervin , Thanks for the quick response. @AndrewO's tip is a bit out of date. This is what I've done so far:

* To install imagemagick 6 on macos: `brew install imagemagick@6`
* I didn't have boost installed so: `brew install boost`
* At that point I got the following error:
```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in utils
VPATH='.' CC='g++' PKG_CONFIG='/usr/local/bin/pkg-config' with_imagemagick='yes' /usr/local/bin/python setup.py build
running build
running build_py
running build_ext
running build_scripts
Making all in src
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -g  -lxml2 -L/usr/local/Cellar/glib/2.64.5/lib -L/usr/local/opt/gettext/lib -lglib-2.0 -lintl -L/usr/local/Cellar/glib/2.64.5/lib -L/usr/local/opt/gettext/lib -lgobject-2.0 -lglib-2.0 -lintl -ledit -lboost_regex -Wl,-E -ldl  -o fmbt fmbt-fmbt.o fmbt-test_engine.o fmbt-log.o fmbt-helper.o fmbt-xrules.g.d_parser.o fmbt-lts_xrules.o fmbt-adapter.o fmbt-awrapper.o fmbt-adapter_model.o fmbt-adapter_mapper.o fmbt-adapter_dummy.o fmbt-adapter_timer.o fmbt-adapter_lib.o fmbt-adapter_rly08btech.o fmbt-heuristic.o fmbt-heuristic_random.o fmbt-heuristic_mrandom.o fmbt-heuristic_greedy.o fmbt-weight.g.d_parser.o fmbt-heuristic_weight.o fmbt-heuristic_include.o fmbt-heuristic_coverage_random.o fmbt-coverage_random.o fmbt-coverage.o fmbt-coverage_exec_filter.o fmbt-coverage_mapper.o fmbt-coverage_tree.o fmbt-coverage_prop.o fmbt-coverage_uniq.o fmbt-filter.g.d_parser.o fmbt-set.g.d_parser.o fmbt-coverage_set.o fmbt-coverage_avoid.o fmbt-coverage_trace.o fmbt-coverage_min.o fmbt-coverage_const.o fmbt-coverage_paths.o fmbt-coverage_report.o fmbt-paths.g.d_parser.o fmbt-coverage_include.o fmbt-coverage_join.o fmbt-coverage_end_condition.o fmbt-coverage_if.o fmbt-coverage_short.o fmbt-covlang.g.d_parser.o fmbt-coverage_market.o fmbt-coverage_restart.o fmbt-coverage_nohistory.o fmbt-coverage_proxy.o fmbt-heuristic_proxy.o fmbt-model.o fmbt-mwrapper.o fmbt-lts.o fmbt-lts.g.d_parser.o fmbt-model_lib.o fmbt-model_yes.o fmbt-conf.g.d_parser.o fmbt-conf.o fmbt-mrules.g.d_parser.o fmbt-policy.o fmbt-alg_bdfs.o fmbt-history.o fmbt-end_condition.o fmbt-date.g.d_parser.o fmbt-null.o fmbt-aal.o fmbt-endhook.o fmbt-coverage_of.o fmbt-random.o fmbt-random_c.o fmbt-random_devrandom.o fmbt-random_supported.o fmbt-function.o fmbt-function_pid.o fmbt-function_const.o fmbt-function_time.o fmbt-function_ustime.o fmbt-params.o fmbt-function_supported.o fmbt-learning.o fmbt-learn_time.o fmbt-learn_action.o fmbt-learn_proxy.o fmbt-readline_wrapper.o fmbt-verdict.o  fmbt-adapter_dlopen.o fmbt-adapter_remote.o fmbt-lts_remote.o fmbt-lts_trace.o fmbt-xrules_remote.o fmbt-coverage_shared.o fmbt-coverage_tema_seq.o fmbt-history_remote.o fmbt-model_remote.o fmbt-aal_java.o fmbt-aal_remote.o fmbt-history_log.o fmbt-history_multi.o fmbt-history_glob.o fmbt-remote.o fmbt-learn_function.o fmbt-function_random.o fmbt-function_array.o d/libdparse.a 
libtool: link: g++ -g -O2 -g -Wl,-E -o fmbt fmbt-fmbt.o fmbt-test_engine.o fmbt-log.o fmbt-helper.o fmbt-xrules.g.d_parser.o fmbt-lts_xrules.o fmbt-adapter.o fmbt-awrapper.o fmbt-adapter_model.o fmbt-adapter_mapper.o fmbt-adapter_dummy.o fmbt-adapter_timer.o fmbt-adapter_lib.o fmbt-adapter_rly08btech.o fmbt-heuristic.o fmbt-heuristic_random.o fmbt-heuristic_mrandom.o fmbt-heuristic_greedy.o fmbt-weight.g.d_parser.o fmbt-heuristic_weight.o fmbt-heuristic_include.o fmbt-heuristic_coverage_random.o fmbt-coverage_random.o fmbt-coverage.o fmbt-coverage_exec_filter.o fmbt-coverage_mapper.o fmbt-coverage_tree.o fmbt-coverage_prop.o fmbt-coverage_uniq.o fmbt-filter.g.d_parser.o fmbt-set.g.d_parser.o fmbt-coverage_set.o fmbt-coverage_avoid.o fmbt-coverage_trace.o fmbt-coverage_min.o fmbt-coverage_const.o fmbt-coverage_paths.o fmbt-coverage_report.o fmbt-paths.g.d_parser.o fmbt-coverage_include.o fmbt-coverage_join.o fmbt-coverage_end_condition.o fmbt-coverage_if.o fmbt-coverage_short.o fmbt-covlang.g.d_parser.o fmbt-coverage_market.o fmbt-coverage_restart.o fmbt-coverage_nohistory.o fmbt-coverage_proxy.o fmbt-heuristic_proxy.o fmbt-model.o fmbt-mwrapper.o fmbt-lts.o fmbt-lts.g.d_parser.o fmbt-model_lib.o fmbt-model_yes.o fmbt-conf.g.d_parser.o fmbt-conf.o fmbt-mrules.g.d_parser.o fmbt-policy.o fmbt-alg_bdfs.o fmbt-history.o fmbt-end_condition.o fmbt-date.g.d_parser.o fmbt-null.o fmbt-aal.o fmbt-endhook.o fmbt-coverage_of.o fmbt-random.o fmbt-random_c.o fmbt-random_devrandom.o fmbt-random_supported.o fmbt-function.o fmbt-function_pid.o fmbt-function_const.o fmbt-function_time.o fmbt-function_ustime.o fmbt-params.o fmbt-function_supported.o fmbt-learning.o fmbt-learn_time.o fmbt-learn_action.o fmbt-learn_proxy.o fmbt-readline_wrapper.o fmbt-verdict.o fmbt-adapter_dlopen.o fmbt-adapter_remote.o fmbt-lts_remote.o fmbt-lts_trace.o fmbt-xrules_remote.o fmbt-coverage_shared.o fmbt-coverage_tema_seq.o fmbt-history_remote.o fmbt-model_remote.o fmbt-aal_java.o fmbt-aal_remote.o fmbt-history_log.o fmbt-history_multi.o fmbt-history_glob.o fmbt-remote.o fmbt-learn_function.o fmbt-function_random.o fmbt-function_array.o -Wl,-bind_at_load  -lxml2 -L/usr/local/Cellar/glib/2.64.5/lib -L/usr/local/opt/gettext/lib -lgobject-2.0 -lglib-2.0 -lintl -ledit -lboost_regex -ldl d/libdparse.a
ld: unknown option: -E
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [fmbt] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
* MacOs doesn't allow the `E` flag on ld, so I fixed the above by changing `src/Makefile` line 1129 from:
    fmbt_LDFLAGS = -g $(JVMLDFLAGS) $(XML2_LIBS) $(GLIB_LIBS) $(GOBJECT_LIBS) $(LIBEDIT_LIBS) -lboost_regex -Wl,-E $(DLINK_OBJ)
to:
    fmbt_LDFLAGS = -g $(JVMLDFLAGS) $(XML2_LIBS) $(GLIB_LIBS) $(GOBJECT_LIBS) $(LIBEDIT_LIBS) -lboost_regex -Wl,-export_dynamic $(DLINK_OBJ)

* And now we're making it all the way to linking:
```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in utils
VPATH='.' CC='g++' PKG_CONFIG='/usr/local/bin/pkg-config' with_imagemagick='yes' /usr/local/bin/python setup.py build
running build
running build_py
running build_ext
running build_scripts
Making all in src
g++ -DHAVE_CONFIG_H -I. -I..  -Wall -pedantic -I d -DDROI -DFMBTBUILDINFO='""' -I/usr/local/Cellar/glib/2.64.5/include/glib-2.0 -I/usr/local/Cellar/glib/2.64.5/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.44/include   -g -O2 -MT remote_adapter_loader-adapter_v4l2.o -MD -MP -MF .deps/remote_adapter_loader-adapter_v4l2.Tpo -c -o remote_adapter_loader-adapter_v4l2.o `test -f 'adapter_v4l2.cc' || echo './'`adapter_v4l2.cc
In file included from adapter_v4l2.cc:23:
./adapter_v4l2.hh:20:10: fatal error: 'linux/videodev2.h' file not found
#include <linux/videodev2.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [remote_adapter_loader-adapter_v4l2.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Any suggestions on how to get around linking `linux/videodev2.h`? I did some searching and haven't had any luck finding the equivalent for MacOS, but I'm far from a MacOS expert.

**Comment by askervin** [comment] 2020-09-09 06:06
I'd suggest just dropping v4l adapter from the build. It's highly unlikely that you'd be running tests against video4linux on your Mac, so there is no need to build native v4l adapter for it either. This will not affect test generation and execution with Python/AAL models and adapters.

You can remove v4l from `src/Sources.mk`:

```
diff --git a/src/Sources.mk b/src/Sources.mk
index 204e83e4..1e11b4b8 100644
--- a/src/Sources.mk
+++ b/src/Sources.mk
@@ -20,7 +20,7 @@ fmbt_droid_SOURCES            = $(COMMON_SOURCES)

 fmbt_aalc_SOURCES = lang.g.d_parser.cc lang.cc helper.cc aalang_cpp.cc aalang_py.cc aalang_py3.cc aalang_java.cc params.cc

-remote_adapter_loader_SOURCES = remote_adapter_loader.cc adapter.cc log.cc adapter_dummy.cc adapter_model.cc adapter_v4l2.cc helper.cc model.cc random.cc function.cc random_c.cc params.cc function_const.cc function_array.cc
+remote_adapter_loader_SOURCES = remote_adapter_loader.cc adapter.cc log.cc adapter_dummy.cc adapter_model.cc helper.cc model.cc random.cc function.cc random_c.cc params.cc function_const.cc function_array.cc

 fmbt_aalp_SOURCES = aalp.ll helper.cc params.cc log.cc
```

**Comment by fkberthold** [comment] 2020-09-09 15:15
More progress, but we're not qutie there yet.

* I removed `adapter_v4l2.cc` as suggested, and ran into the problem with MacOS's version of `ld` not accepting `-E` again.  
    * To fix this I replaced all instances of `-E` with `-export_dynamic` in `src/Makefile.am`
* **Make completed succesfully.**
* I tried to run `sudo make install` and got the following:
```
VPATH='.' CC='g++' PKG_CONFIG='/usr/local/bin/pkg-config' with_imagemagick='yes' /usr/local/bin/python setup.py build
Package MagickCore was not found in the pkg-config search path.
Perhaps you should add the directory containing `MagickCore.pc'
to the PKG_CONFIG_PATH environment variable
No package 'MagickCore' found
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    eye4graphcs_buildflags = pkg_config("MagickCore")
  File "setup.py", line 55, in pkg_config
    o = check_output([_pkg_config, "--libs", "--cflags", package])
  File "setup.py", line 14, in check_output
    raise subprocess.CalledProcessError(exitstatus, args[0])
subprocess.CalledProcessError: Command '['/usr/local/bin/pkg-config', '--libs', '--cflags', 'MagickCore']' returned non-zero exit status 1
make[1]: *** [all-local] Error 1
make: *** [install-recursive] Error 1
```
    * To fix this I installed imagemagick: `brew install imagemagick`
* After trying to run make install again I got:
```
Making install in utils
VPATH='.' CC='g++' PKG_CONFIG='/usr/local/bin/pkg-config' with_imagemagick='yes' /usr/local/bin/python setup.py build
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    eye4graphcs_buildflags = pkg_config("MagickCore")
  File "setup.py", line 68, in pkg_config
    % (arg, o))
ValueError: Unexpected pkg-config output: "-Xpreprocessor" in "-Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.10-29/include/ImageMagick-7 -L/usr/local/Cellar/imagemagick/7.0.10-29/lib -lMagickCore-7.Q16HDRI
"
make[1]: *** [all-local] Error 1
make: *** [install-recursive] Error 1
```

Any suggestions?

**Comment by askervin** [comment] 2020-09-10 07:55
Thanks for your reports and patience so far, @fkberthold!

I changed -E to -export-dynamic in Makefile.am, and fixed setup.py pkg_config caller to be less picky about what pkg-config prints. Changes are in the devel branch. (I'd also like to include v4l adapter to the build only on Linux, but didn't get my change quite working yet.)

However, I'm afraid these will not solve your problem with imagemagick. The problem was that pkg-config did not find imagemagick version 6 configuration (MagickCore.pc). As a last step you installed imagemagick 7 and pkg-config was able to find its .pc file, but the bad thing is that it will link against imagemagick 7, and that most likely fails due to API break between 6 and 7.

My suggestion would be to go back to imagemagick 6 and try to `find /usr/local -name MagickCore.pc` and add its directory to PKG_CONFIG_PATH. In other words (understandable by Bash), assuming that brew installs imagemagick 6 pc file somewhere under /usr/local,
```
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$(dirname "$(find /usr/local -name MagickCore.pc)")
```

**Comment by fkberthold** [comment] 2020-09-10 15:22
We have progress once again. I already have imagemagick 6 installed.
* I tried just using the code given above:
```
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$(dirname "$(find /usr/local -name MagickCore.pc)")
```

* Make install seemed to work this time. When I tried to run `fmbt-editor` it failed to find it so I tried `/usr/local/bin/fmbt-editor` and got:
```
fmbt-editor: Error importing Qt4 bindings from "PySide": No module named PySide.QtCore
Install PySide Python bindings for Qt4 or try different -q parameter.
```

* For this, from past experience, I know I need qt4 & pyside so:
```brew install qt@4
sudo pip install pyside```

It failed because it couldn't find qmake:

```
Collecting pyside
  Downloading https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz (9.3MB)
     |████████████████████████████████| 9.3MB 3.2MB/s 
Building wheels for collected packages: pyside
  Building wheel for pyside (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-87R3tg --python-tag cp27
       cwd: /private/tmp/pip-install-triHo0/pyside/
  Complete output (5 lines):
  Removing /private/tmp/pip-install-triHo0/pyside/pyside_package
  running bdist_wheel
  running build
  Python architecture is 64bit
  error: Failed to find qmake. Please specify the path to qmake with --qmake parameter.
  ----------------------------------------
  ERROR: Failed building wheel for pyside
  Running setup.py clean for pyside
Failed to build pyside
Installing collected packages: pyside
    Running setup.py install for pyside ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-y4zwNw/install-record.txt --single-version-externally-managed --compile
         cwd: /private/tmp/pip-install-triHo0/pyside/
    Complete output (5 lines):
    Removing /private/tmp/pip-install-triHo0/pyside/pyside_package
    running install
    running build
    Python architecture is 64bit
    error: Failed to find qmake. Please specify the path to qmake with --qmake parameter.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-triHo0/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-y4zwNw/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

I added qmake to my path and tried to install again:
```
export PATH=$PATH:/usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin/
sudo pip install pyside
```

I've deadended with this error:
```
Collecting pyside
  Downloading https://files.pythonhosted.org/packages/36/ac/ca31db6f2225844d37a41b10615c3d371587677efd074db29855e7035de6/PySide-1.2.4.tar.gz (9.3MB)
     |████████████████████████████████| 9.3MB 2.5MB/s 
Building wheels for collected packages: pyside
  Building wheel for pyside (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@2/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-3wJJPA/pyside/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-3wJJPA/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-EHyqWX --python-tag cp27
       cwd: /private/tmp/pip-install-3wJJPA/pyside/
  Complete output (76 lines):
  Removing /private/tmp/pip-install-3wJJPA/pyside/pyside_package
  running bdist_wheel
  running build
  Python architecture is 64bit
  Inserting path "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/bin" to environment
  Inserting path "/usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin" to environment
  Inserting path "/private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release/bin" to environment
  ==============================
  Package version: 1.2.4
  Build type: Release
  Build tests: False
  ---
  Make path: /usr/bin/make
  Make generator: Unix Makefiles
  Make jobs:
  ---
  Script directory: /private/tmp/pip-install-3wJJPA/pyside
  Sources directory: /private/tmp/pip-install-3wJJPA/pyside/sources
  Build directory: /private/tmp/pip-install-3wJJPA/pyside/pyside_build/py2.7-qt4.8.7-64bit-release
  Install directory: /private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release
  Python site-packages install directory: /private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release/lib/python2.7/site-packages
  ---
  Python executable: /usr/local/opt/python@2/bin/python2.7
  Python includes: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/include/python2.7
  Python library: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
  Python prefix: /usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7
  Python scripts: /usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/bin
  ---
  Qt qmake: /usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin/qmake
  Qt version: 4.8.7
  Qt bins: /usr/local/bin
  Qt plugins: /usr/local/lib/qt4/plugins
  ---
  OpenSSL libs: None
  ==============================
  Creating build folder /private/tmp/pip-install-3wJJPA/pyside/pyside_build/py2.7-qt4.8.7-64bit-release...
  Creating install folder /private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release...
  Building module shiboken...
  Creating module build folder /private/tmp/pip-install-3wJJPA/pyside/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken...
  Configuring module shiboken (/private/tmp/pip-install-3wJJPA/pyside/sources/shiboken)...
  Running process: /usr/local/bin/cmake -G "Unix Makefiles" -DQT_QMAKE_EXECUTABLE=/usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release /private/tmp/pip-install-3wJJPA/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/usr/local/opt/python@2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/include
  /usr/local/bin/cmake -G Unix Makefiles -DQT_QMAKE_EXECUTABLE=/usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin/qmake -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/private/tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release /private/tmp/pip-install-3wJJPA/pyside/sources/shiboken -DPYTHON_EXECUTABLE=/usr/local/opt/python@2/bin/python2.7 -DPYTHON_INCLUDE_DIR=/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -DPYTHON_LIBRARY=/usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DALTERNATIVE_QT_INCLUDE_DIR=/usr/local/include
  -- The C compiler identification is AppleClang 11.0.3.11030032
  -- The CXX compiler identification is AppleClang 11.0.3.11030032
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning at /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindQt4.cmake:618 (message):
    /usr/local/Cellar/qt@4/4.8.7_6.reinstall/bin/qmake reported QT_INSTALL_LIBS
    as "/usr/local/lib" but QtCore could not be found there.  Qt is NOT
    installed correctly for the target build environment.
  Call Stack (most recent call first):
    CMakeLists.txt:9 (find_package)
  
  
  -- Found PythonLibs: /usr/local/opt/python@2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.17", minimum required is "2.6")
  -- !!! The generated bindings will be installed on /tmp/pip-install-3wJJPA/pyside/pyside_install/py2.7-qt4.8.7-64bit-release/lib/python2.7/site-packages, is it right!?
  -- Found LibXml2: /usr/lib/libxml2.dylib (found suitable version "2.9.4", minimum required is "2.6.32")
  -- Found LibXslt: /usr/lib/libxslt.dylib (found suitable version "1.1.29", minimum required is "1.1.19")
  Qt QTGUI library not found.
  Qt QTXML library not found.
  Qt QTCORE library not found.
  CMake Error at ApiExtractor/CMakeLists.txt:82 (qt4_add_resources):
    Unknown CMake command "qt4_add_resources".
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-3wJJPA/pyside/pyside_build/py2.7-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeOutput.log".
  error: Error configuring shiboken
  ----------------------------------------
  ERROR: Failed building wheel for pyside
```

Any suggestions for my next move?

**Comment by fkberthold** [comment] 2020-09-15 19:51
I had a bit of time for debugging this afternoon.  The core of the problem on the previous step was 'dot' wasn't available.

'dot' is part of the graphviz package, which is available on homebrew, so:

```
brew install graphviz
```

It installed without a hitch. I think we're up and running. I haven't tried actually generating tests or running them remotely. I'll put in notes when I find out how it works.

**Comment by fkberthold** [comment] 2020-09-15 20:00
I found another minor issue, gnuplot is also necessary for the "Distrib" and "Coverage" tabs.  When I ran

```
brew install gnuplot
```

I got:
```
==> Pouring pyside-5.15.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pyside/5.15.1: 717 files, 46.8MB
Removing: /usr/local/Cellar/pyside/5.15.0... (696 files, 45.1MB)
Removing: /Users/fberthold/Library/Caches/Homebrew/pyside--5.15.0.catalina.bottle.tar.gz... (11.9MB)
==> Checking for dependents of upgraded formulae...
Error: No such file or directory - /usr/local/Cellar/pyside/5.15.0
```

At the end. I tried to run gnuplot anyway, and it seems to be working, the tabs are now functional.

**Comment by askervin** [comment] 2021-01-28 08:49
OS X users can use fMBT by building a docker image, see fMBT devel branch:

https://github.com/intel/fMBT/blob/devel/Dockerfile

Big thanks to @fkberthold!

**Closed** 2021-01-28 08:49 UTC
